### ISSUE TITLE
Crashes at start

### ISSUE THREAD

**Issue by offline2007** [Orthae/DiscordTriggerStuff#1]
![2](https://user-images.githubusercontent.com/35119853/46890089-03c49100-ce66-11e8-88f9-b06428071ee9.PNG)
![unbenannt](https://user-images.githubusercontent.com/35119853/46890094-07581800-ce66-11e8-8a0c-7cc79df514bf.PNG)

OS: Windows 10 (German)
Newest Java Update

**Comment by Orthae** [comment]
It might be related to Java 11 not containing JavaFX library anymore, you can try to fix it yourself by installing Java 10 JRE(remember to delete Java 11 beforehand). I will look today into it and release fixed version.

**Comment by offline2007** [comment]
Yeah, I'm on java 8.
Didn't even know there was a Java 10 version, as Java says I'm up to date. Sorry!

I just updated manually to java 10 and now it works. Thanks for the great work!

**Comment by Orthae** [comment]
Beta 3 is now working with Java 8 JRE. Issue resolved.
